// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjr-Ql-PJJ3KXbPSgUJhWPrq76LhkfFhY',
    appId: '1:19749906888:web:94ae31aa7949046c4bb8fd',
    messagingSenderId: '19749906888',
    projectId: 'yusaninharita',
    authDomain: 'yusaninharita.firebaseapp.com',
    storageBucket: 'yusaninharita.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd4vY0LQjQNq8ywLyXtmxtrzFHgnEuehA',
    appId: '1:19749906888:android:64919b2c20abbc3a4bb8fd',
    messagingSenderId: '19749906888',
    projectId: 'yusaninharita',
    storageBucket: 'yusaninharita.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGOVz1Q2sSAjIQwypCuXrkgRPc5ZJVj-I',
    appId: '1:19749906888:ios:9b8393689f28c4af4bb8fd',
    messagingSenderId: '19749906888',
    projectId: 'yusaninharita',
    storageBucket: 'yusaninharita.appspot.com',
    iosBundleId: 'com.example.haritaProje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGOVz1Q2sSAjIQwypCuXrkgRPc5ZJVj-I',
    appId: '1:19749906888:ios:3dec85a5484b9b714bb8fd',
    messagingSenderId: '19749906888',
    projectId: 'yusaninharita',
    storageBucket: 'yusaninharita.appspot.com',
    iosBundleId: 'com.example.haritaProje.RunnerTests',
  );
}
